---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  
- name: uninstall httpd
  yum: 
    name: httpd
    state: absent
    
- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file
  
- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file
  
- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: "{{ gitlab_download_validate_certs }}"
  when: not gitlab_file.stat.exists
  
- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  when: not gitlab_file.stat.exists

- name: Define the Gitlab package name.
  set_fact:
    gitlab_package_name: "{{ gitlab_edition }}{{ gitlab_package_version_separator }}{{ gitlab_version }}"
  when: gitlab_version != ''
- name: Install GitLab
  package:
    name: "{{ gitlab_package_name | default(gitlab_edition) }}"
    state: present
  when: not gitlab_file.stat.exists

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Copy GitLab configuration file.
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab

- name: Create gitlab configuration backup directory
  file:
    path: /secret/gitlab/backups
    state: directory
    owner: root
    group: root
    mode: 0755 

- name: Copy over gitlab server backup script
  copy:
    src: gitlab-server-backup.sh
    dest: /root/gitlab-server-backup.sh
    owner: root
    group: root
    mode: 0755

- name: Create cronjob to run gitlab backup script @ AEST0215 or UTC1615
  cron:
    name: "backup gitlab to local"
    minute: "15"
    hour: "16"
    weekday: "2-6"
    job: "/root/gitlab-server-backup.sh"